[paths]
logs             = $SCRATCH/davai/logs
default_mtooldir = $SCRATCH/mtool/$LOGNAME
venvs            = ~nlcr/venvs/davai
#IAL_repository   = ~/repositories/IAL
#IAL_bundle_repository   = ~/repositories/IAL-bundle

[packages]
# vortex-1 : the path has to be the root of the project
#vortex        = ~sos/vortex/vortex-olive-dev
vortex        = ~nlcr/git/gitfr/vortex
