[defaults]
usecase = NRV
# default origin repo from which DAVAI is cloned for each editable experiment, if not specified by argument
#davai_remote_repo = https://github.com/ACCORD-NWP/DAVAI
davai_remote_repo = https://github.com/romick-knmi/DAVAI
IAL_bundle_repository = https://github.com/ACCORD-NWP/IAL-bundle
# for shelves archiving:
davai_alias_user = mary
davai_alias_arch_subdir = davai

[paths]
IAL_repository = ~/git/github/romick-knmi/IAL
experiments = ~/davai/experiments
logs        = ~/davai/logs

