forecasts:
    - standalone_forecast_alaro0_antwrp1300                # standalone forecasts = "pure" toy models forecasts without any extra component (DFI, IAU, Fullpos...)
    - standalone_forecast_alaro1_antwrp1300
    # Not present in CY49T2 - standalone_forecast_alaro1_sfx_chmh2325
    - standalone_forecast_arome_corsica2500
    - standalone_forecast_arpege_globaltst149c24
    - standalone_forecast_arpege_nosfx_globaltst149c24
    - standalone_forecast_ifs_global21
    - canonical_forecast_arpege_global798c22               # canonical forecasts = close to operations, including extra components
    - canonical_forecast_arpege_apl_global798c22

assim:
    - OOPSBSM_4D_arpege  # BSM = Bator+Screening+Minim
    - OOPSBA1_4D_arpege  # BSM = Bator+AllInOne
    - CNT0BSM_4D_arpege  # BSM = Bator+Screening+Minim
    - BsC_arpege  # BsC = Bator_surf+Canari
    - BSM_3D_arome  # BSM = Bator+Screening+Minim
    # FIXME: - BA1_3D_arome  # BSM = Bator+Screening+Minim

# mixs: jobs containing several tasks of various families
#mixs:
#    - PF  # Prep-Forecast (using older PGD)
#    - PPF  # PGD-Prep-Forecast (using new PGD)

objects:
    - Bmat_arpege  # Construction and reading of a B-matrix using an ensemble, EnVar unit tests
    - ModelTL_arpege # TL model, adjoint test

fullpos:
    - Fp_lbc  # Fp_lbc = Fullpos creation of LBC files - currently on arpege boundaries work properly

surfex:
    - PP_geo_arome   # PP_geo_arome  = PGD+Prep on a range of LAM geometries
    - PP_geo_arpege  # PP_geo_arpege = PGD+Prep on a range of Gaussian geometries

